/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package magscan;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;

/**
 *
 * @author bijoy
 */
public class MagScan extends javax.swing.JFrame {

    /**
     * Creates new form MagScan
     */    
    
    public MagScan() {
        initComponents();
        
        //set scanImageJFileChooser as invisible
        scanImageJFileChooser.setVisible(false);        
        
        //populate imageCategory Comobox
        this.populateImageCategory(0,"");
        
    }    
    
    /**
     * Class to hold the values for category
     * values are id and string
     */
    class Item
    {
        private int id;
        private String description;

        public Item(int id, String description)
        {
            this.id = id;
            this.description = description;
        }

        public int getId()
        {
            return id;
        }

        public String getDescription()
        {
            return description;
        }

        public String toString()
        {
            return description;
        }
    }    
    
    /**
     * Populate Image Category JComboBox
     * @param parentID
     * @param showLevel 
     */
    private void populateImageCategory(int parentID,String showLevel){
        
        //DB Connection
        String sql = "SELECT * FROM category WHERE parent_id="+parentID;        
        
        try{
            ResultSet rs = DataService.getResultSet(sql);
            // ResultSet is initially before the first data set
            while (rs.next()) {
                //add each item to combobox
                imageCategoryJComboBox.addItem(new Item(rs.getInt("id"), showLevel+rs.getString("name")));
                this.populateImageCategory(rs.getInt("id"),showLevel+"->");
            }  
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }       
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scanTabPane = new javax.swing.JTabbedPane();
        scanJPanel = new javax.swing.JPanel();
        addImageJButton = new javax.swing.JButton();
        scanImageJFileChooser = new javax.swing.JFileChooser();
        imageNameJLabel = new javax.swing.JLabel();
        imageNameJTextField = new javax.swing.JTextField();
        imageDescJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imageDescJTextArea = new javax.swing.JTextArea();
        imageCategoryJLabel = new javax.swing.JLabel();
        imageCategoryJComboBox = new javax.swing.JComboBox();
        searchJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addImageJButton.setText("Add Scanned Image");
        addImageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageJButtonActionPerformed(evt);
            }
        });

        imageNameJLabel.setText("Name");

        imageDescJLabel.setText("Description");

        imageDescJTextArea.setColumns(20);
        imageDescJTextArea.setRows(5);
        jScrollPane1.setViewportView(imageDescJTextArea);

        imageCategoryJLabel.setText("Category");

        imageCategoryJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        imageCategoryJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageCategoryJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scanJPanelLayout = new javax.swing.GroupLayout(scanJPanel);
        scanJPanel.setLayout(scanJPanelLayout);
        scanJPanelLayout.setHorizontalGroup(
            scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scanJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(scanJPanelLayout.createSequentialGroup()
                        .addComponent(imageNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scanJPanelLayout.createSequentialGroup()
                        .addComponent(addImageJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scanImageJFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scanJPanelLayout.createSequentialGroup()
                        .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageDescJLabel)
                            .addComponent(imageCategoryJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(imageCategoryJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        scanJPanelLayout.setVerticalGroup(
            scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scanJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scanImageJFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addImageJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageNameJLabel)
                    .addComponent(imageNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageDescJLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(scanJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageCategoryJLabel)
                    .addComponent(imageCategoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        scanTabPane.addTab("Scan", scanJPanel);

        javax.swing.GroupLayout searchJPanelLayout = new javax.swing.GroupLayout(searchJPanel);
        searchJPanel.setLayout(searchJPanelLayout);
        searchJPanelLayout.setHorizontalGroup(
            searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        searchJPanelLayout.setVerticalGroup(
            searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        scanTabPane.addTab("Search", searchJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scanTabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scanTabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addImageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageJButtonActionPerformed
    
        scanImageJFileChooser.setVisible(true);
        int returnVal = scanImageJFileChooser.showOpenDialog(MagScan.this);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION){
            System.out.println(scanImageJFileChooser.getSelectedFile().getPath());
        }
        
    }//GEN-LAST:event_addImageJButtonActionPerformed

    private void imageCategoryJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageCategoryJComboBoxActionPerformed

        JComboBox comboBox = (JComboBox)evt.getSource();
        Item item = (Item)comboBox.getSelectedItem();
        System.out.println( item.getId() + " : " + item.getDescription() );        
        
    }//GEN-LAST:event_imageCategoryJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagScan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImageJButton;
    private javax.swing.JComboBox imageCategoryJComboBox;
    private javax.swing.JLabel imageCategoryJLabel;
    private javax.swing.JLabel imageDescJLabel;
    private javax.swing.JTextArea imageDescJTextArea;
    private javax.swing.JLabel imageNameJLabel;
    private javax.swing.JTextField imageNameJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser scanImageJFileChooser;
    private javax.swing.JPanel scanJPanel;
    private javax.swing.JTabbedPane scanTabPane;
    private javax.swing.JPanel searchJPanel;
    // End of variables declaration//GEN-END:variables
}
